require('plugins/p-weather')
require('plugins/p-mason')
require('plugins/p-discord')
-- require('plugins/p-lsp')
require('plugins/p-text')
require('plugins/p-telescope')
require('plugins/p-treesitter')
require('plugins/p-harpoon')
require('plugins/p-color')
require('plugins/p-cmp')
