[env]
TERM = "xterm-256color"

[window]
padding = { x = 20, y = 0 }
dynamic_padding = false
opacity = 1.0
decorations = "buttonless"
title = "Alacritty"
class = { instance = "Alacritty", general = "Alacritty" }

[scrolling]
history = 5000

[font]
size = 23.0
offset = { x = 0, y = 1 }

[font.normal]
family = "SF Mono"
style = "Regular"

[font.bold]
family = "Menlo"
style = "Bold"

[font.italic]
family = "Menlo"
style = "Italic"

[font.bold_italic]
family = "Menlo"
style = "Bold Italic"

[colors.primary]
background = "0x16181a"
foreground = "0xffffff"

[colors.cursor]
background = "0xffffff"
foreground = "0x16181a"

[colors.selection]
background = "0x3c4048"
foreground = "0xffffff"

[colors.normal]
black = "0x16181a"
red = "0xff6e5e"
green = "0x5eff6c"
yellow = "0xf1ff5e"
blue = "0x5ea1ff"
magenta = "0xbd5eff"
cyan = "0x5ef1ff"
white = "0xffffff"

[colors.bright]
black = "0x3c4048"
red = "0xff6e5e"
green = "0x5eff6c"
yellow = "0xf1ff5e"
blue = "0x5ea1ff"
magenta = "0xbd5eff"
cyan = "0x5ef1ff"
white = "0xffffff"

[cursor]
style = "Block"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "Insert"
mods = "Shift"
action = "PasteSelection"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "F11"
mods = "None"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "Paste"
mods = "None"
action = "Paste"

[[keyboard.bindings]]
key = "Copy"
mods = "None"
action = "Copy"

[[keyboard.bindings]]
key = "L"
mods = "Control"
action = "ClearLogNotice"

[[keyboard.bindings]]
key = "L"
mods = "Control"
chars = "\u000c"

[[keyboard.bindings]]
key = "PageUp"
mods = "None"
action = "ScrollPageUp"
mode = "~Alt"

[[keyboard.bindings]]
key = "PageDown"
mods = "None"
action = "ScrollPageDown"
mode = "~Alt"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
action = "ScrollToTop"
mode = "~Alt"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
action = "ScrollToBottom"
mode = "~Alt"

[[keyboard.bindings]]
key = "Back"
mods = "Command"
chars = "\u0015"

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001bb"

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001bf"

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u001bOH"
mode = "AppCursor"

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u001bOF"
mode = "AppCursor"

